version: '3.4'

services:
  # client:
  #   image: client:1.0
  #   build: .
  #   ports:
  #     - 3000:3000
  # server:
  #   image: server:1.0
  #   build: .
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment: 
      - MONGODB_DATABASE="managetimeworking"
    volumes:
      - ./data:/data/db
    ports:
        - "27018:27017"
