version: '3.4'

services:
  # client:
  #   image: client:1.0
  #   build: .
  #   ports:
  #     - 3000:3000
  # server:
  #   image: server:1.0
  #   build: .
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mysql 
  mysql:
    image: mysql:5.7
    container_name: mysqldb
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: managetimeworking
      MYSQL_USER: linhbui98
      MYSQL_PASSWORD: 2321998
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
        - "3306:3306"
